absl-py==1.4.0
aiohttp==3.8.3
aiohttp-retry==2.5.1
aiosignal==1.2.0
antlr4-python3-runtime==4.9.3
appdirs==1.4.4
async-timeout==4.0.2
asynctest==0.13.0
atpublic==2.3
attrs==22.2.0
cached-property==1.5.2
cachetools==4.2.4
captum==0.6.0
certifi==2022.12.7
cffi==1.15.1
charset-normalizer==2.0.12
click==8.0.4
colorama==0.4.5
commonmark==0.9.1
configobj==5.0.8
contextvars==2.4
cycler==0.11.0
dataclasses==0.8
decorator==4.4.2
dictdiffer==0.9.0
diskcache==5.4.0
distro==1.8.0
docker-pycreds==0.4.0
dpath==2.0.7
dulwich==0.20.50
dvc==2.8.1
et-xmlfile==1.1.0
flatten-dict==0.4.2
flufl.lock==3.2
frozenlist==1.2.0
fsspec==2022.1.0
ftfy==6.0.3
funcy==1.18
future==0.18.3
gitdb==4.0.9
GitPython==3.1.18
glob2==0.7
google-auth==2.16.0
google-auth-oauthlib==0.4.6
grandalf==0.6
grpcio==1.48.2
hydra-core==1.3.1
idna==3.4
idna-ssl==1.1.0
imagecodecs==2020.5.30
imageio==2.15.0
immutables==0.19
importlib-metadata==4.8.3
importlib-resources==5.4.0
kiwisolver==1.3.1
lightning-bolts==0.4.0
mailchecker==5.0.7
Markdown==3.3.7
matplotlib==3.3.4
multidict==5.2.0
nanotime==0.5.2
networkx==2.5.1
numpy==1.19.5
oauthlib==3.2.2
omegaconf==2.3.0
openpyxl==3.1.0
packaging==21.3
pathspec==0.8.1
pathtools==0.1.2
phonenumbers==8.13.5
Pillow==8.4.0
ply==3.11
protobuf==3.19.6
psutil==5.9.4
pyasn1==0.4.8
pyasn1-modules==0.2.8
pycparser==2.21
pyDeprecate==0.3.1
pydot==1.4.2
pygit2==1.6.1
Pygments==2.14.0
pygtrie==2.5.0
pyparsing==2.4.7
python-benedict==0.26.0
python-dateutil==2.8.2
python-dotenv==0.20.0
python-fsutil==0.10.0
python-slugify==6.1.2
pytorch-lightning==1.5.10
PyWavelets==1.1.1
PyYAML==6.0
requests==2.27.1
requests-oauthlib==1.3.1
rich==12.6.0
rsa==4.9
ruamel.yaml==0.17.21
ruamel.yaml.clib==0.2.7
scikit-image==0.17.2
scipy==1.5.4
sentry-sdk==1.15.0
setproctitle==1.2.3
shortuuid==1.0.11
shtab==1.5.7
six==1.16.0
smmap==5.0.0
tabulate==0.8.10
tensorboard==2.10.1
tensorboard-data-server==0.6.1
tensorboard-plugin-wit==1.8.1
text-unidecode==1.3
tifffile==2020.9.3
toml==0.10.2
torch==1.9.0+rocm4.2
torchmetrics==0.8.2
torchvision==0.10.0+rocm4.2
tqdm==4.64.1
typing_extensions==4.1.1
urllib3==1.26.14
voluptuous==0.13.1
wandb==0.13.9
wcwidth==0.2.6
Werkzeug==2.0.3
xlrd==2.0.1
xmltodict==0.13.0
yarl==1.7.2
zc.lockfile==2.0
zipp==3.6.0
